name: GitHub Wiki Sidebar
description: Generates a sidebar for a GitHub wiki.
author: MilkyWare

inputs:
  separator:
    description: 'The separator used to determine the hierarchy in the sidebar.'
    required: false
    default: '__'
  exclude:
    description: 'A comma-separated list of files or directories to exclude from the sidebar.'
    required: false
    default: ''
  order:
    description: 'A comma-separated list of files or directories in the desired order for the sidebar.'
    required: false
    default: ''
  wiki-path:
    description: The path to the GitHub wiki content. Defaults to the current directory.
    required: false
    default: .

outputs:
  sidebar:
    description: 'The generated sidebar content in Markdown format.'
    value: ${{ steps.generate-sidebar.outputs.sidebar_content }}

runs:
  using: 'composite'
  steps:
    - shell: pwsh
      id: generate-sidebar
      working-directory: ${{ inputs.wiki-path }}
      run: |
        $exclude = @"
        ${{ inputs.exclude }}
        "@ -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ }

        $order = @"
        ${{ inputs.order }}
        "@ -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ }

        ${{ github.action_path }}/GenerateWikiSidebar.ps1 `
          -Separator '${{ inputs.separator }}' `
          -Exclude $exclude `
          -Order $order
