name: Generate Sidebar

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }}/repo
      WIKI_PATH: ${{ github.workspace }}/wiki
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_PATH }}

      - name: Checkout Wiki
        uses: actions/checkout@v6
        id: checkout-wiki
        with:
          repository: ${{ github.repository }}.wiki
          path: ${{ env.WIKI_PATH }}

      - name: Clean Wiki Repo
        shell: pwsh
        working-directory: ${{ env.WIKI_PATH }}
        run: |
          git ls-files | ForEach-Object {Remove-Item -Path $_ }

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Published Wiki
          repository: ${{ env.WIKI_PATH }}
