name: Generate Sidebar

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      WIKI_REPO_PATH: ${{ github.workspace }}/wiki
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v6
        with:
          path: repo

      - name: Checkout Wiki
        uses: actions/checkout@v6
        id: checkout-wiki
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Clean Wiki Repo
        shell: pwsh
        run: |
          git ls-files | ForEach-Object {Remove-Item -Path $_ }